### ISSUE TITLE
aeroo report availabe for odoo 12 ?

### ISSUE THREAD

**Issue by ngdangtruong** [aeroo/aeroo_reports#120]
I hear no body ask aeroo report for odoo 12
But i try to install it and i can not
```Traceback (most recent call last):
  File "/opt/odoo/odoo12/odoo/http.py", line 654, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo12/odoo/http.py", line 312, in _handle_exception
    raise ValueError("Wrong value for %s: %r" % (self, value))
ValueError: Wrong value for ir.actions.report.in_format: 'oo-odt'```

Please help me

**Comment by sraps** [comment]
Aeroo reports will be ported and released for Odoo v12. I am working on that.

**Comment by dupski** [comment]
I see the "unworkable" text thats been added to the readme. Are there some fundamental issues that are preventing Aeroo from working with v12? or is it just a case of finishing the port?

Keen to help if I can as we'd like to move some old v7 customers to v12 :)

**Comment by dupski** [comment]
Just to update for others that find this ticket. There is a fork of Aeroo that seems to work on Odoo 12 already:
https://github.com/ingadhoc/aeroo_reports

But it appears that many folks are now using "py3o" which is supported by the Odoo Community Association:
https://github.com/OCA/reporting-engine/tree/12.0/report_py3o
https://apps.odoo.com/apps/modules/browse?search=py3o

Props to @sraps and the team though for their work on Aeroo - its still running in production for many of our customers and working great :)

**Comment by diezcode** [comment]
@dupski This fork isn't working on odoo12 enterprise. I tested it today.
There is still some work to do for v12.
But thx
