### ISSUE TITLE
Aeroo-docs installation -  No module named 'uno'

### ISSUE THREAD

**Issue by lbertran** [aeroo/aeroo_reports#124]
Hi, 

I am installing odoo 11 on Debian 9 (bitnami). I will use modules for Argentina and the requirements are Aeroo-reports.

Now update apt-get and install python3-uno and unoconv.

Running

sudo python3 / opt / aeroo / aeroo_docs / aeroo-docs start -c /etc/aeroo-docs.conf

I get the following error:

Traceback (most recent call last):
  File "/ opt / aeroo / aeroo_docs / aeroo-docs", line 42, in <module>
    from aeroo_docs_fncs import OfficeService
  File "/opt/aeroo/aeroo_docs/aeroo_docs_fncs.py", line 37, in <module>
    from DocumentConverter import DocumentConverter, DocumentConversionException
  File "/opt/aeroo/aeroo_docs/DocumentConverter.py", line 34, in <module>
    import one
ModuleNotFoundError: No module named 'one'

**Comment by sraps** [comment]
Hi,unoconv is definitely not needed. That is for sure, neither aeroo nor aeroo-docs use it.Something strange with "import uno" it should be "uno" instead of "one".You can test if python3 uno module is installed correctly by running import uno in python3 interactive console.Check your environment, maybe.BR,Kaspars2019. gada 7. dec. 19:59, lbertran <notifications@github.com> rakstīja:Hi,
I am installing odoo 11. I will use modules for Argentina and the requirements are Aeroo-reports.
Now update apt-get and install python3-uno and unoconv.
Running
sudo python3 / opt / aeroo / aeroo_docs / aeroo-docs start -c /etc/aeroo-docs.conf
I get the following error:
Traceback (most recent call last):
File "/ opt / aeroo / aeroo_docs / aeroo-docs", line 42, in 
from aeroo_docs_fncs import OfficeService
File "/opt/aeroo/aeroo_docs/aeroo_docs_fncs.py", line 37, in 
from DocumentConverter import DocumentConverter, DocumentConversionException
File "/opt/aeroo/aeroo_docs/DocumentConverter.py", line 34, in 
import one
ModuleNotFoundError: No module named 'one'

**Comment by lbertran** [comment]
Thanks for answering. It's UNO, "one" was a translation error.

As you can see I try to install UNO and the message is that it is already installed. Then I run import UNO and the message is that the module does not exist

```
bitnami@debian:~$ sudo apt-get install python3-uno
Reading package lists... Done
Building dependency tree
Reading state information... Done
python3-uno is already the newest version (1:5.2.7-1+deb9u11).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
bitnami@debian:~$ python3
Python 3.7.4 (default, Oct 17 2019, 10:22:20)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-11)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import uno
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'uno'
```

then I ran `pip3 install uno` successfully.

I run again `yes | sudo python3 /opt/aeroo/aeroo_docs/aeroo-docs start -c /etc/aeroo-docs.conf `and the error is `ModuleNotFoundError: No module named 'base'`

I ran `pip3 install base` successfully.

I run again `yes | sudo python3 /opt/aeroo/aeroo_docs/aeroo-docs start -c /etc/aeroo-docs.conf` and the error is 

```
Traceback (most recent call last):
  File "/opt/aeroo/aeroo_docs/aeroo-docs", line 42, in <module>
    from aeroo_docs_fncs import OfficeService
  File "/opt/aeroo/aeroo_docs/aeroo_docs_fncs.py", line 37, in <module>
    from DocumentConverter import DocumentConverter, DocumentConversionException
  File "/opt/aeroo/aeroo_docs/DocumentConverter.py", line 34, in <module>
    import uno
  File "/opt/bitnami/python/lib/python3.7/site-packages/uno/__init__.py", line 4, in <module>
    from base import Element, Css, Payload, UnoBaseFeature, UnoBaseField
ImportError: cannot import name 'Element' from 'base' (/opt/bitnami/python/lib/python3.7/site-packages/base/__init__.py)
```

Not sure if `pip3 install uno` is correct

**Comment by sraps** [comment]
Hi,Please check:# pip3 -V# python3 -VBr,Kaspars2019. gada 8. dec. 15:49, lbertran <notifications@github.com> rakstīja:Thanks for answering. It's UNO, "one" was a translation error.
As you can see I try to install UNO and the message is that it is already installed. Then I run import UNO and the message is that the module does not exist
bitnami@debian:~$ sudo apt-get install python3-uno
Reading package lists... Done
Building dependency tree
Reading state information... Done
python3-uno is already the newest version (1:5.2.7-1+deb9u11).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
bitnami@debian:~$ python3
Python 3.7.4 (default, Oct 17 2019, 10:22:20)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-11)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import uno
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'uno'

then I ran pip3 install uno successfully.
I run again yes | sudo python3 /opt/aeroo/aeroo_docs/aeroo-docs start -c /etc/aeroo-docs.conf and the error is ModuleNotFoundError: No module named 'base'
I ran pip3 install base successfully.
I run again yes | sudo python3 /opt/aeroo/aeroo_docs/aeroo-docs start -c /etc/aeroo-docs.conf and the error is
Traceback (most recent call last):
  File "/opt/aeroo/aeroo_docs/aeroo-docs", line 42, in <module>
    from aeroo_docs_fncs import OfficeService
  File "/opt/aeroo/aeroo_docs/aeroo_docs_fncs.py", line 37, in <module>
    from DocumentConverter import DocumentConverter, DocumentConversionException
  File "/opt/aeroo/aeroo_docs/DocumentConverter.py", line 34, in <module>
    import uno
  File "/opt/bitnami/python/lib/python3.7/site-packages/uno/__init__.py", line 4, in <module>
    from base import Element, Css, Payload, UnoBaseFeature, UnoBaseField
ImportError: cannot import name 'Element' from 'base' (/opt/bitnami/python/lib/python3.7/site-packages/base/__init__.py)

Not sure if pip3 install uno is correct

**Comment by sraps** [comment]
Please do run without python3 in front of executable. Try just # aeroo-docs start2019. gada 8. dec. 15:49, lbertran <notifications@github.com> rakstīja:Thanks for answering. It's UNO, "one" was a translation error.
As you can see I try to install UNO and the message is that it is already installed. Then I run import UNO and the message is that the module does not exist
bitnami@debian:~$ sudo apt-get install python3-uno
Reading package lists... Done
Building dependency tree
Reading state information... Done
python3-uno is already the newest version (1:5.2.7-1+deb9u11).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
bitnami@debian:~$ python3
Python 3.7.4 (default, Oct 17 2019, 10:22:20)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-11)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import uno
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'uno'

then I ran pip3 install uno successfully.
I run again yes | sudo python3 /opt/aeroo/aeroo_docs/aeroo-docs start -c /etc/aeroo-docs.conf and the error is ModuleNotFoundError: No module named 'base'
I ran pip3 install base successfully.
I run again yes | sudo python3 /opt/aeroo/aeroo_docs/aeroo-docs start -c /etc/aeroo-docs.conf and the error is
Traceback (most recent call last):
  File "/opt/aeroo/aeroo_docs/aeroo-docs", line 42, in <module>
    from aeroo_docs_fncs import OfficeService
  File "/opt/aeroo/aeroo_docs/aeroo_docs_fncs.py", line 37, in <module>
    from DocumentConverter import DocumentConverter, DocumentConversionException
  File "/opt/aeroo/aeroo_docs/DocumentConverter.py", line 34, in <module>
    import uno
  File "/opt/bitnami/python/lib/python3.7/site-packages/uno/__init__.py", line 4, in <module>
    from base import Element, Css, Payload, UnoBaseFeature, UnoBaseField
ImportError: cannot import name 'Element' from 'base' (/opt/bitnami/python/lib/python3.7/site-packages/base/__init__.py)

Not sure if pip3 install uno is correct

**Comment by lbertran** [comment]
Versions:

`bitnami@debian:~$ pip3 -V`
`pip 19.0.3 from /opt/bitnami/python/lib/python3.7/site-packages/pip (python 3.7)`
`bitnami@debian:~$ python3 -V`
`Python 3.7.4`


Just aeroo-docs start
```
bitnami@debian:/opt/aeroo/aeroo_docs$ sudo ./aeroo-docs start
Traceback (most recent call last):
  File "./aeroo-docs", line 42, in <module>
    from aeroo_docs_fncs import OfficeService
  File "/opt/aeroo/aeroo_docs/aeroo_docs_fncs.py", line 37, in <module>
    from DocumentConverter import DocumentConverter, DocumentConversionException
  File "/opt/aeroo/aeroo_docs/DocumentConverter.py", line 34, in <module>
    import uno
  File "/opt/bitnami/python/lib/python3.7/site-packages/uno/__init__.py", line 4, in <module>
    from base import Element, Css, Payload, UnoBaseFeature, UnoBaseField
ImportError: cannot import name 'Element' from 'base' (/opt/bitnami/python/lib/python3.7/site-packages/base/__init__.py)
```

**Comment by lbertran** [comment]
Hi @sraps 

Could you advance on this issue? thank you very much

**Comment by sraps** [comment]
Ok, it seems you have not received my last message, check below....There are some mismatch with names of uno in pip3, did not know it. In pip3 uno is totally different library.so now please remove uno using pip3# pip3 uninstall unoThen make sure installing uno using aptitude# apt install python3-unoThen should be fine using aeroo-docsBR,Kaspars2019. gada 13. dec. 19:59, lbertran <notifications@github.com> rakstīja:Hi @sraps
Could you advance on this issue? thank you very much

**Comment by lbertran** [comment]
Thank you very much @sraps . I tried what you told me and the output was:

```
bitnami@debian:~$ sudo pip3 uninstall uno
Uninstalling uno-0.3.3:
  Would remove:
    /opt/bitnami/python/lib/python3.7/site-packages/uno-0.3.3.dist-info/*
    /opt/bitnami/python/lib/python3.7/site-packages/uno/*
Proceed (y/n)? Y
  Successfully uninstalled uno-0.3.3
bitnami@debian:~$ sudo aptitude install python3-uno
python3-uno is already installed at the requested version (1:5.2.7-1+deb9u11)
python3-uno is already installed at the requested version (1:5.2.7-1+deb9u11)
No packages will be installed, upgraded, or removed.
0 packages upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B of archives. After unpacking 0 B will be used.

bitnami@debian:~$ sudo python3 /opt/aeroo/aeroo_docs/aeroo-docs start -c /etc/aeroo-docs.conf
Traceback (most recent call last):
  File "/opt/aeroo/aeroo_docs/aeroo-docs", line 42, in <module>
    from aeroo_docs_fncs import OfficeService
  File "/opt/aeroo/aeroo_docs/aeroo_docs_fncs.py", line 37, in <module>
    from DocumentConverter import DocumentConverter, DocumentConversionException
  File "/opt/aeroo/aeroo_docs/DocumentConverter.py", line 34, in <module>
    import uno
ModuleNotFoundError: No module named 'uno'
```
Something is missing

**Comment by lbertran** [comment]
Hi @sraps  how are you? Can you find something else about this issue? 

Thanks you very much
