### ISSUE TITLE
Cannot install a module with aeroo report with latest commit

### ISSUE THREAD

**Issue by alexis-via** [aeroo/aeroo_reports#26]
I just update my aeroo master branch with the latest commit made today. But, when I try to install a module that contain an aeroo report (this module could be installed without problem with the code of last week), it crashes:

```
2014-12-03 20:23:33,605 4579 INFO o8_test1 report_aeroo: registering report.dilicom.csv.purchase.order (purchase.order)
None
> /home/alexis/new_boite/dev/odoo/openerp/api.py(395)new_api()
-> result = [method(rec, *args, **kwargs) for rec in self]
(Pdb) c2014-12-03 20:23:38,355 4579 INFO o8_test1 openerp.modules.loading: loading 1 modules...

2014-12-03 20:23:38,561 4579 ERROR o8_test1 openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/home/alexis/new_boite/dev/odoo/openerp/http.py", line 517, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/alexis/new_boite/dev/odoo/openerp/http.py", line 538, in dispatch
    result = self._call_function(**self.params)
  File "/home/alexis/new_boite/dev/odoo/openerp/http.py", line 294, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/alexis/new_boite/dev/odoo/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/alexis/new_boite/dev/odoo/openerp/http.py", line 291, in checked_call
    return self.endpoint(*a, **kw)
  File "/home/alexis/new_boite/dev/odoo/openerp/http.py", line 754, in __call__
    return self.method(*args, **kw)
  File "/home/alexis/new_boite/dev/odoo/openerp/http.py", line 387, in response_wrap
    response = f(*args, **kw)
  File "/home/alexis/new_boite/dev/odoo/addons/web/controllers/main.py", line 953, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/alexis/new_boite/dev/odoo/addons/web/controllers/main.py", line 941, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/home/alexis/new_boite/dev/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/alexis/new_boite/dev/odoo/openerp/addons/base/module/module.py", line 450, in button_immediate_install
    return self._button_immediate_function(cr, uid, ids, self.button_install, context=context)
  File "/home/alexis/new_boite/dev/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/alexis/new_boite/dev/odoo/openerp/addons/base/module/module.py", line 498, in _button_immediate_function
    registry = openerp.modules.registry.RegistryManager.new(cr.dbname, update_module=True)
  File "/home/alexis/new_boite/dev/odoo/openerp/modules/registry.py", line 341, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/alexis/new_boite/dev/odoo/openerp/modules/loading.py", line 358, in load_modules
    loaded_modules, update_module)
  File "/home/alexis/new_boite/dev/odoo/openerp/modules/loading.py", line 263, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/home/alexis/new_boite/dev/odoo/openerp/modules/loading.py", line 182, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/home/alexis/new_boite/dev/odoo/openerp/modules/loading.py", line 118, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/home/alexis/new_boite/dev/odoo/openerp/tools/convert.py", line 901, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/home/alexis/new_boite/dev/odoo/openerp/tools/convert.py", line 987, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/home/alexis/new_boite/dev/odoo/openerp/tools/convert.py", line 853, in parse
    self._tags[rec.tag](self.cr, rec, n, mode=mode)
  File "/home/alexis/new_boite/dev/odoo/openerp/tools/convert.py", line 763, in _tag_record
    id = self.pool['ir.model.data']._update(cr, self.uid, rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode, context=rec_context )
  File "/home/alexis/new_boite/dev/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/alexis/new_boite/dev/odoo/openerp/addons/base/ir/ir_model.py", line 1059, in _update
    res_id = model_obj.create(cr, uid, values, context=context)
  File "/home/alexis/new_boite/dev/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/alexis/new_boite/dev/odoo/openerp/api.py", line 332, in old_api
    result = method(recs, *args, **kwargs)
  File "/home/alexis/new_boite/dev/aeroo-80/report_aeroo/report_xml.py", line 544, in create
    res_id = super(report_xml, self).create(vals)
  File "/home/alexis/new_boite/dev/odoo/openerp/api.py", line 235, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/alexis/new_boite/dev/odoo/openerp/models.py", line 4004, in create
    self._fields[key].determine_inverse(record)
  File "/home/alexis/new_boite/dev/odoo/openerp/fields.py", line 889, in determine_inverse
    self.inverse(records)
  File "/home/alexis/new_boite/dev/odoo/openerp/api.py", line 235, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/alexis/new_boite/dev/odoo/openerp/api.py", line 395, in new_api
    result = [method(rec, *args, **kwargs) for rec in self]
ParseError: "_report_content_inv() takes exactly 4 arguments (1 given)" while parsing /home/alexis/new_boite/dev/dilicom/purchase_dilicom_csv/report.xml:12, near
<record id="dilicom_csv_purchase_order" model="ir.actions.report.xml">
    <field name="name">Dilicom Commande CSV</field>
    <field name="model">purchase.order</field>
    <field name="report_name">dilicom.csv.purchase.order</field>
    <field name="report_type">aeroo</field>
    <field name="in_format">genshi-raw</field>
    <field name="report_rml">purchase_dilicom_csv/report/dilicom_purchase_order_csv.txt</field>
    <field name="parser_state">default</field>
    <field name="tml_source">file</field>
    <field name="multi" eval="0"/>
    <field name="out_format" ref="report_aeroo.report_mimetypes_raw"/>
    <field name="content_fname">txt</field>
    <field name="fallback_false" eval="0"/>
    <field name="attachment_use" eval="0"/>
    <field name="styles_mode">default</field>
</record>
```

If you want to reproduce the crash, you can get my module purchase_dilicom_csv from https://github.com/akretion/dilicom

**Comment by alexis-via** [comment]
This bug has been fixed long ago, let's close it !
