### ISSUE TITLE
report_aeroo v8 crashs the export of translation files

### ISSUE THREAD

**Issue by alexis-via** [aeroo/aeroo_reports#3]
When I start odoo v8 to export a translation file with report_aeroo installed (up-to-date version, master branch), I get a crash:

$ ./odoo.py -c ../config-80 -d my_database --i18n-export=/tmp/stay.po --modules=stay

Traceback (most recent call last):
  File "./odoo.py", line 162, in <module>
    main()
  File "./odoo.py", line 159, in main
    openerp.cli.main()
  File "/home/openerp/travail8/odoo/openerp/cli/__init__.py", line 71, in main
    o.run(args)
  File "/home/openerp/travail8/odoo/openerp/cli/server.py", line 174, in run
    main(args)
  File "/home/openerp/travail8/odoo/openerp/cli/server.py", line 149, in main
    export_translation()
  File "/home/openerp/travail8/odoo/openerp/cli/server.py", line 121, in export_translation
    config["translate_modules"] or ["all"], buf, fileformat, cr)
  File "/home/openerp/travail8/odoo/openerp/tools/translate.py", line 508, in trans_export
    translations = trans_generate(lang, modules, cr)
  File "/home/openerp/travail8/aeroo/report_aeroo/translate.py", line 172, in extend_trans_generate
    for field_name,field_def in obj._table._columns.items():
AttributeError: 'str' object has no attribute '_columns'

This bug seems easy to fix : on line 172 of report_aeroo/translate.py, it seems that you simply have to change "obj._table._columns.items()" by "obj._columns.items()"

But, once you have made this first fix, you get another crash:

$ ./odoo.py -c ../config-80 -d barroux8-test6 --i18n-export=/tmp/stay.po --modules=stay
[...]
Traceback (most recent call last):
  File "./odoo.py", line 162, in <module>
    main()
  File "./odoo.py", line 159, in main
    openerp.cli.main()
  File "/home/openerp/travail8/odoo/openerp/cli/__init__.py", line 71, in main
    o.run(args)
  File "/home/openerp/travail8/odoo/openerp/cli/server.py", line 174, in run
    main(args)
  File "/home/openerp/travail8/odoo/openerp/cli/server.py", line 149, in main
    export_translation()
  File "/home/openerp/travail8/odoo/openerp/cli/server.py", line 121, in export_translation
    config["translate_modules"] or ["all"], buf, fileformat, cr)
  File "/home/openerp/travail8/odoo/openerp/tools/translate.py", line 508, in trans_export
    translations = trans_generate(lang, modules, cr)
  File "/home/openerp/travail8/aeroo/report_aeroo/translate.py", line 103, in extend_trans_generate
    for t in trans_parse_view(d):
TypeError: trans_parse_view() takes exactly 2 arguments (1 given)

The function trans_parse_view is defined in odoo/openerp/tools/translate.py line 555 and its proto is:

def trans_parse_view(element, callback):
""" Helper method to recursively walk an etree document representing a
        regular view and call ``callback(term)`` for each translatable term
        that is found in the document.

        :param ElementTree element: root of etree document to extract terms from
        :param callable callback: a callable in the form ``f(term, source_line)``,
            that will be called for each extracted term.
"""
But I don't know how to fix this second issue.

**Comment by nicothebrush** [comment]
Hi, got the same error during export translation, seems on obj ir.models and ir.models.fields, ir.cron ir.act.window
I try to "try except pass" the loop but got another error, here 2 pic.:
![aeroo1](https://cloud.githubusercontent.com/assets/703949/6570611/e4301b8e-c6fd-11e4-90c9-25c6e061d5b7.png)

![aeroo2](https://cloud.githubusercontent.com/assets/703949/6570614/ec2fdeb4-c6fd-11e4-82c1-6e39e0cd5a28.png)

**Comment by alexis-via** [comment]
my PR with the fix has been merged in master.
