### ISSUE TITLE
Aeroo Report EMPTY

### ISSUE THREAD

**Issue by diezcode** [aeroo/aeroo_reports#61]
I installed all like this step:
https://www.odoo.com/fr_FR/forum/help-1/question/8-0-how-can-i-install-the-official-aeroo-reports-alistek-for-odoo-version-8-solved-installation-script-76044

My Problem is that the generated PDF is blank. It says an error with the PDF File when I open it with a pdf-programm.

I need help.

**Comment by lukebranch** [comment]
@diezcode ,

I'm not involved with Aeroo Reports/Alistek directly, but I wrote that script and installation guide, so maybe I can help.

Could you post the report template you've used for creating the PDF? This might help in troubleshooting what's wrong.

**Comment by diezcode** [comment]
The template is bank. It should print that blank template. but what I get is this : 
![unbenannt](https://cloud.githubusercontent.com/assets/7522882/8953534/8a469598-35df-11e5-943c-f4f4da3c5150.PNG)

I have an installation on an other server that it works fine, but I have done that in january. So my problem right now is that the printed pdf is broken or it can't be open.

**Comment by lukebranch** [comment]
@diezcode ,

Could you run :

sudo tail -f /var/log/odoo/odoo-server.log

in another terminal window and do the process again and see if there are any messages in the logs?

The error message you sent me is showing that there is no connection to aeroo-docs server.

**Comment by diezcode** [comment]
None
2015-07-29 09:22:39,070 22224 INFO test_diez report_aeroo: End total process report.Rechnung-Template (account.invoice), total elapsed time: 0.187715053558
None
2015-07-29 09:22:39,134 22224 INFO test_diez werkzeug: 127.0.0.1 - - [29/Jul/2015 09:22:39] "POST /web/report HTTP/1.0" 200 -
2015-07-29 09:22:39,863 22224 INFO test_diez werkzeug: 127.0.0.1 - - [29/Jul/2015 09:22:39] "POST /web/dataset/call_kw/account.invoice/search_read HTTP/1.0" 200 -
2015-07-29 09:22:39,911 22224 INFO test_diez werkzeug: 127.0.0.1 - - [29/Jul/2015 09:22:39] "POST /web/dataset/call_kw/res.partner/name_get HTTP/1.0" 200 -
2015-07-29 09:22:39,923 22224 INFO test_diez werkzeug: 127.0.0.1 - - [29/Jul/2015 09:22:39] "POST /web/dataset/call_kw/account.invoice/read_followers_data HTTP/1.0" 200 -
2015-07-29 09:22:39,950 22224 INFO test_diez werkzeug: 127.0.0.1 - - [29/Jul/2015 09:22:39] "POST /web/dataset/call_kw/mail.message/message_read HTTP/1.0" 200 -
2015-07-29 09:22:40,004 22224 INFO test_diez werkzeug: 127.0.0.1 - - [29/Jul/2015 09:22:40] "POST /web/dataset/search_read HTTP/1.0" 200 -
2015-07-29 09:22:40,027 22224 INFO test_diez werkzeug: 127.0.0.1 - - [29/Jul/2015 09:22:40] "POST /web/dataset/call_kw/account.invoice/message_get_subscription_data HTTP/1.0" 200 -
2015-07-29 09:22:40,047 22224 INFO test_diez werkzeug: 127.0.0.1 - - [29/Jul/2015 09:22:40] "POST /web/dataset/call_kw/mail.message/set_message_read HTTP/1.0" 200 -
2015-07-29 09:22:43,184 22224 INFO test_diez werkzeug: 127.0.0.1 - - [29/Jul/2015 09:22:43] "POST /longpolling/poll HTTP/1.0" 200 -
2015-07-29 09:23:18,312 22224 INFO test_diez werkzeug: 127.0.0.1 - - [29/Jul/2015 09:23:18] "POST /web/action/load HTTP/1.0" 200 -
2015-07-29 09:23:18,402 22224 INFO test_diez werkzeug: 127.0.0.1 - - [29/Jul/2015 09:23:18] "POST /web/menu/load_needaction HTTP/1.0" 200 -
2015-07-29 09:23:18,450 22224 INFO test_diez werkzeug: 127.0.0.1 - - [29/Jul/2015 09:23:18] "POST /web/dataset/call_kw/ir.module.module/fields_view_get HTTP/1.0" 200 -
2015-07-29 09:23:18,486 22224 INFO test_diez werkzeug: 127.0.0.1 - - [29/Jul/2015 09:23:18] "POST /web/dataset/call_kw/ir.module.module/fields_view_get HTTP/1.0" 200 -
2015-07-29 09:23:18,515 22224 INFO test_diez werkzeug: 127.0.0.1 - - [29/Jul/2015 09:23:18] "POST /web/dataset/call_kw/ir.filters/get_filters HTTP/1.0" 200 -
2015-07-29 09:23:18,525 22224 INFO test_diez werkzeug: 127.0.0.1 - - [29/Jul/2015 09:23:18] "POST /web/dataset/call_kw/ir.module.module/fields_get HTTP/1.0" 200 -
2015-07-29 09:23:18,608 22224 INFO test_diez werkzeug: 127.0.0.1 - - [29/Jul/2015 09:23:18] "POST /web/dataset/search_read HTTP/1.0" 200 -
2015-07-29 09:23:20,390 22224 INFO test_diez werkzeug: 127.0.0.1 - - [29/Jul/2015 09:23:20] "POST /web/action/load HTTP/1.0" 200 -
2015-07-29 09:23:20,444 22224 INFO test_diez werkzeug: 127.0.0.1 - - [29/Jul/2015 09:23:20] "POST /web/dataset/call_kw/docs_config.installer/fields_view_get HTTP/1.0" 200 -
2015-07-29 09:23:20,540 22224 INFO test_diez werkzeug: 127.0.0.1 - - [29/Jul/2015 09:23:20] "POST /web/dataset/call_kw/docs_config.installer/default_get HTTP/1.0" 200 -
2015-07-29 09:23:20,581 22224 INFO test_diez werkzeug: 127.0.0.1 - - [29/Jul/2015 09:23:20] "POST /web/dataset/call_kw/docs_config.installer/onchange HTTP/1.0" 200 -
2015-07-29 09:23:22,145 22224 INFO test_diez werkzeug: 127.0.0.1 - - [29/Jul/2015 09:23:22] "POST /web/dataset/call_kw/docs_config.installer/create HTTP/1.0" 200 -
2015-07-29 09:23:22,188 22224 INFO test_diez werkzeug: 127.0.0.1 - - [29/Jul/2015 09:23:22] "POST /web/dataset/call_kw/docs_config.installer/search_read HTTP/1.0" 200 -
2015-07-29 09:23:22,261 22224 INFO test_diez urllib3.connectionpool: Starting new HTTP connection (1): localhost
2015-07-29 09:23:22,266 22224 INFO test_diez urllib3.connectionpool: Starting new HTTP connection (1): localhost
2015-07-29 09:23:22,375 22224 INFO test_diez werkzeug: 127.0.0.1 - - [29/Jul/2015 09:23:22] "POST /web/dataset/call_button HTTP/1.0" 200 -
2015-07-29 09:23:22,426 22224 INFO test_diez werkzeug: 127.0.0.1 - - [29/Jul/2015 09:23:22] "POST /web/dataset/call_kw/docs_config.installer/fields_view_get HTTP/1.0" 200 -
2015-07-29 09:23:22,488 22224 INFO test_diez werkzeug: 127.0.0.1 - - [29/Jul/2015 09:23:22] "POST /web/dataset/call_kw/docs_config.installer/read HTTP/1.0" 200 -
2015-07-29 09:23:22,489 22224 INFO test_diez werkzeug: 127.0.0.1 - - [29/Jul/2015 09:23:22] "POST /web/menu/load_needaction HTTP/1.0" 200 -
2015-07-29 09:23:26,668 22224 INFO test_diez werkzeug: 127.0.0.1 - - [29/Jul/2015 09:23:26] "POST /web/dataset/call_kw/docs_config.installer/search_read HTTP/1.0" 200 -
2015-07-29 09:23:29,821 22224 INFO test_diez werkzeug: 127.0.0.1 - - [29/Jul/2015 09:23:29] "POST /web/action/load HTTP/1.0" 200 -
2015-07-29 09:23:29,861 22224 INFO test_diez werkzeug: 127.0.0.1 - - [29/Jul/2015 09:23:29] "POST /web/menu/load_needaction HTTP/1.0" 200 -
2015-07-29 09:23:29,935 22224 INFO test_diez werkzeug: 127.0.0.1 - - [29/Jul/2015 09:23:29] "POST /web/dataset/call_kw/account.invoice/fields_view_get HTTP/1.0" 200 -
2015-07-29 09:23:29,995 22224 INFO test_diez werkzeug: 127.0.0.1 - - [29/Jul/2015 09:23:29] "POST /web/dataset/call_kw/account.invoice/fields_get HTTP/1.0" 200 -
2015-07-29 09:23:29,996 22224 INFO test_diez werkzeug: 127.0.0.1 - - [29/Jul/2015 09:23:29] "POST /web/dataset/call_kw/ir.filters/get_filters HTTP/1.0" 200 -
2015-07-29 09:23:30,013 22224 INFO test_diez werkzeug: 127.0.0.1 - - [29/Jul/2015 09:23:30] "POST /web/dataset/call_kw/account.invoice/fields_view_get HTTP/1.0" 200 -
2015-07-29 09:23:30,162 22224 INFO test_diez werkzeug: 127.0.0.1 - - [29/Jul/2015 09:23:30] "POST /web/dataset/call_kw/account.invoice/fields_view_get HTTP/1.0" 200 -
2015-07-29 09:23:30,657 22224 INFO test_diez werkzeug: 127.0.0.1 - - [29/Jul/2015 09:23:30] "POST /web/dataset/search_read HTTP/1.0" 200 -
2015-07-29 09:23:31,658 22224 ERROR test_diez openerp.addons.base.ir.ir_cron: Unexpected exception while processing cron job {'function': u'run_all', 'create_uid': 1, 'args': u'()', 'user_id': 1, 'name': u'Webservice Handler', 'interval_type': u'minutes', 'numbercall': -1, 'nextcall': '2015-06-19 08:14:00.459208', 'priority': 2, 'model': u'bss.webservice_handler', 'doall': False, 'write_date': '2015-06-19 08:17:43.010536', 'active': True, 'create_date': '2015-06-19 08:17:43.010536', 'interval_number': 1, 'write_uid': 1, 'id': 18}
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/openerp/addons/base/ir/ir_cron.py", line 250, in _acquire_job
    registry[cls._name]._process_job(job_cr, job, lock_cr)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/base/ir/ir_cron.py", line 163, in _process_job
    nextcall = fields.datetime.context_timestamp(job_cr, job['user_id'], datetime.strptime(job['nextcall'], DEFAULT_SERVER_DATETIME_FORMAT))
  File "/usr/lib/python2.7/_strptime.py", line 328, in _strptime
    data_string[found.end():])
ValueError: unconverted data remains: .459208
2015-07-29 09:23:32,083 22224 INFO test_diez werkzeug: 127.0.0.1 - - [29/Jul/2015 09:23:32] "POST /calendar/notify HTTP/1.0" 200 -
2015-07-29 09:23:32,514 22224 INFO test_diez werkzeug: 127.0.0.1 - - [29/Jul/2015 09:23:32] "POST /web/dataset/call_kw/account.invoice/fields_view_get HTTP/1.0" 200 -
2015-07-29 09:23:32,937 22224 INFO test_diez werkzeug: 127.0.0.1 - - [29/Jul/2015 09:23:32] "POST /web/dataset/call_kw/account.invoice/read HTTP/1.0" 200 -
2015-07-29 09:23:33,007 22224 INFO test_diez werkzeug: 127.0.0.1 - - [29/Jul/2015 09:23:33] "POST /web/dataset/search_read HTTP/1.0" 200 -
2015-07-29 09:23:33,010 22224 INFO test_diez werkzeug: 127.0.0.1 - - [29/Jul/2015 09:23:33] "POST /web/dataset/search_read HTTP/1.0" 200 -
2015-07-29 09:23:33,012 22224 INFO test_diez werkzeug: 127.0.0.1 - - [29/Jul/2015 09:23:33] "POST /web/dataset/search_read HTTP/1.0" 200 -
2015-07-29 09:23:33,021 22224 INFO test_diez werkzeug: 127.0.0.1 - - [29/Jul/2015 09:23:33] "POST /web/dataset/search_read HTTP/1.0" 200 -
2015-07-29 09:23:33,045 22224 INFO test_diez werkzeug: 127.0.0.1 - - [29/Jul/2015 09:23:33] "POST /web/dataset/call_kw/res.partner/name_get HTTP/1.0" 200 -
2015-07-29 09:23:33,068 22224 INFO test_diez werkzeug: 127.0.0.1 - - [29/Jul/2015 09:23:33] "POST /web/dataset/call_kw/res.company/name_search HTTP/1.0" 200 -
2015-07-29 09:23:33,101 22224 INFO test_diez werkzeug: 127.0.0.1 - - [29/Jul/2015 09:23:33] "POST /web/dataset/call_kw/account.invoice/read_followers_data HTTP/1.0" 200 -
2015-07-29 09:23:33,133 22224 INFO test_diez werkzeug: 127.0.0.1 - - [29/Jul/2015 09:23:33] "POST /web/dataset/search_read HTTP/1.0" 200 -
2015-07-29 09:23:33,140 22224 INFO test_diez werkzeug: 127.0.0.1 - - [29/Jul/2015 09:23:33] "POST /web/dataset/call_kw/mail.message/message_read HTTP/1.0" 200 -
2015-07-29 09:23:33,209 22224 INFO test_diez werkzeug: 127.0.0.1 - - [29/Jul/2015 09:23:33] "POST /longpolling/poll HTTP/1.0" 200 -
2015-07-29 09:23:33,214 22224 INFO test_diez werkzeug: 127.0.0.1 - - [29/Jul/2015 09:23:33] "POST /web/dataset/call_kw/account.invoice/message_get_subscription_data HTTP/1.0" 200 -
2015-07-29 09:23:33,332 22224 INFO test_diez werkzeug: 127.0.0.1 - - [29/Jul/2015 09:23:33] "POST /web/dataset/call_kw/mail.message/set_message_read HTTP/1.0" 200 -
2015-07-29 09:23:33,501 22224 INFO test_diez werkzeug: 127.0.0.1 - - [29/Jul/2015 09:23:33] "POST /web/dataset/call_kw/account.invoice.line/read HTTP/1.0" 200 -
2015-07-29 09:23:33,540 22224 INFO test_diez werkzeug: 127.0.0.1 - - [29/Jul/2015 09:23:33] "POST /web/dataset/call_kw/account.tax/name_get HTTP/1.0" 200 -
2015-07-29 09:23:33,595 22224 INFO test_diez werkzeug: 127.0.0.1 - - [29/Jul/2015 09:23:33] "POST /web/dataset/call_kw/account.tax/name_get HTTP/1.0" 200 -
2015-07-29 09:23:38,208 22224 INFO test_diez werkzeug: 127.0.0.1 - - [29/Jul/2015 09:23:38] "POST /web/action/load HTTP/1.0" 200 -
2015-07-29 09:23:38,343 22224 INFO test_diez report_aeroo: Start process report.Rechnung-Template (account.invoice)
None
2015-07-29 09:23:38,414 22224 INFO test_diez urllib3.connectionpool: Starting new HTTP connection (1): localhost
2015-07-29 09:23:38,420 22224 INFO test_diez urllib3.connectionpool: Starting new HTTP connection (1): localhost
2015-07-29 09:23:38,504 22224 INFO test_diez report_aeroo: End process report.Rechnung-Template (account.invoice), elapsed time: 0.160385131836
None
2015-07-29 09:23:38,504 22224 INFO test_diez report_aeroo: End total process report.Rechnung-Template (account.invoice), total elapsed time: 0.160783052444
None
2015-07-29 09:23:38,594 22224 INFO test_diez werkzeug: 127.0.0.1 - - [29/Jul/2015 09:23:38] "POST /web/report HTTP/1.0" 200 -
2015-07-29 09:23:39,314 22224 INFO test_diez werkzeug: 127.0.0.1 - - [29/Jul/2015 09:23:39] "POST /web/dataset/call_kw/account.invoice/search_read HTTP/1.0" 200 -
2015-07-29 09:23:39,355 22224 INFO test_diez werkzeug: 127.0.0.1 - - [29/Jul/2015 09:23:39] "POST /web/dataset/call_kw/res.partner/name_get HTTP/1.0" 200 -
2015-07-29 09:23:39,367 22224 INFO test_diez werkzeug: 127.0.0.1 - - [29/Jul/2015 09:23:39] "POST /web/dataset/call_kw/account.invoice/read_followers_data HTTP/1.0" 200 -
2015-07-29 09:23:39,407 22224 INFO test_diez werkzeug: 127.0.0.1 - - [29/Jul/2015 09:23:39] "POST /web/dataset/call_kw/mail.message/message_read HTTP/1.0" 200 -
2015-07-29 09:23:39,422 22224 INFO test_diez werkzeug: 127.0.0.1 - - [29/Jul/2015 09:23:39] "POST /web/dataset/call_kw/account.invoice.line/read HTTP/1.0" 200 -
2015-07-29 09:23:39,433 22224 INFO test_diez werkzeug: 127.0.0.1 - - [29/Jul/2015 09:23:39] "POST /web/dataset/call_kw/account.invoice/message_get_subscription_data HTTP/1.0" 200 -
2015-07-29 09:23:39,458 22224 INFO test_diez werkzeug: 127.0.0.1 - - [29/Jul/2015 09:23:39] "POST /web/dataset/call_kw/mail.message/set_message_read HTTP/1.0" 200 -
2015-07-29 09:23:39,467 22224 INFO test_diez werkzeug: 127.0.0.1 - - [29/Jul/2015 09:23:39] "POST /web/dataset/call_kw/account.tax/name_get HTTP/1.0" 200 -
2015-07-29 09:23:39,579 22224 INFO test_diez werkzeug: 127.0.0.1 - - [29/Jul/2015 09:23:39] "POST /web/dataset/search_read HTTP/1.0" 200 -
2015-07-29 09:24:23,343 22224 INFO test_diez werkzeug: 127.0.0.1 - - [29/Jul/2015 09:24:23] "POST /longpolling/poll HTTP/1.0" 200 -
2015-07-29 09:24:32,737 22224 ERROR test_diez openerp.addons.base.ir.ir_cron: Unexpected exception while processing cron job {'function': u'run_all', 'create_uid': 1, 'args': u'()', 'user_id': 1, 'name': u'Webservice Handler', 'interval_type': u'minutes', 'numbercall': -1, 'nextcall': '2015-06-19 08:14:00.459208', 'priority': 2, 'model': u'bss.webservice_handler', 'doall': False, 'write_date': '2015-06-19 08:17:43.010536', 'active': True, 'create_date': '2015-06-19 08:17:43.010536', 'interval_number': 1, 'write_uid': 1, 'id': 18}
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/openerp/addons/base/ir/ir_cron.py", line 250, in _acquire_job
    registry[cls._name]._process_job(job_cr, job, lock_cr)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/base/ir/ir_cron.py", line 163, in _process_job
    nextcall = fields.datetime.context_timestamp(job_cr, job['user_id'], datetime.strptime(job['nextcall'], DEFAULT_SERVER_DATETIME_FORMAT))
  File "/usr/lib/python2.7/_strptime.py", line 328, in _strptime
    data_string[found.end():])
ValueError: unconverted data remains: .459208

**Comment by diezcode** [comment]
When I make a new installation, with this aeroo Installation steps, it creates the same problem.....

**Comment by diezcode** [comment]
I tested the same database in another server with the same report_aeroo modul. I have no problem there.

**Comment by lukebranch** [comment]
@diezcode ,

Have you made any changes to the invoice template? Please explain in detail what you have setup so far to receive that error message.

Are you having trouble printing to XLS, ODS, DOC, etc., or only PDF?

**Comment by diezcode** [comment]
No I don't have any changes. 
I installed all like in the link previouse. I test the same installation later with an older WKHTMLTOPDF Version. 
Because I don't know exactly what WKHTMLTOPDF version I used in this installation to get the error message. 
In the other system it's the 0.12.1 and everything works fine.

**Comment by diezcode** [comment]
Ok , I tested this with wkhtmltopdf 0.12.1 , but the same. everytime the pdf is empty. I don't get it....

**Comment by lukebranch** [comment]
@diezcode ,

This is quite strange. I've got multiple instances of Aeroo running that have been built with that script.

I can try to reproduce it on my end when I have some time, however i'm quite busy at the moment so this could take awhile.

If you've got a dev instance that I can connect to via SSH and the web interface this might be better, as I can sift through logs, etc. to see if I can find what the issue is. Alternatively if you'd like to email me a copy of your logs (/var/log/odoo/odoo-server.log) to odoocommunitywidgets@gmail.com i'd be happy to take a look.

Preferably if you choose to email me the logs try to reproduce the error and then immediately take a copy of the log file to send to me as it'll have more useful info in there and I won't need to sift through thousands of log-file lines.

**Comment by sraps** [comment]
Hi, @diezcode 

could you verify there's all the dependencies met with your installation, and then the versions of modules. WKHTMLTOPDF is not related to Aeroo in any way. In other words it is not used.

BTW. I am having trouble reply to your request from our webpage. Your server says "host XXX.net[XXX] refused to talk to me"...

**Comment by diezcode** [comment]
on the server that it works:
root 30655 1 0 09:38 ? 00:00:00 python3 /etc/init.d/aeroo-docs restart

on the other server that it doesn't works:

root 5005 1 0 10:02 ? 00:00:00 python3 /opt/aeroo/aeroo_docs/aeroo-docs start -c /etc/init.d/aeroo-docs.conf

**Comment by diezcode** [comment]
Ok I tested this on an other Server with an other Odoo Installation.
To FIX this issue, just restart the server with 
"sudo shutdown -r now"
Then it works! Thanks to all for the help !

**Comment by lukebranch** [comment]
@diezcode ,

I just wanted to double-check, was this issue due to any issues with the script, or was it just a simple case of running the script and then restarting after it's done?

I'd just like to know if I need to make any revisions.

**Comment by diezcode** [comment]
@lukebranch 
It was that you need to make a server restart, after the script. And then you can connect to aeroo-docs.

**Comment by lukebranch** [comment]
@diezcode ,

Thanks for letting me know. I've now setup a prompt with a Y/N option to prompt the user to restart the server after the script is done.

Choose yes (y) and the script will run:

sudo shutdown -r now

for you. 

I think it'll make it a bit more obvious that it's a requirement to people running the script, as it may have been a bit ambiguous before.

**Comment by yuriqp** [comment]
I had the exact same weird problem. I didn't use the script but I followed similar steps. Surprisingly, at least for me, restarting with "shutdown -r now" also solved my problem!!

**Comment by diezcode** [comment]
Information:
An other problem can be, if you have an Ubuntu Firewall and that the port 8989 is not open for localhost for odoo to connect to aeroo-docs.
